/**
 * Meraki AutoChain — New Inspection
 */
const API_BASE = "http://localhost:5000/api";

document.addEventListener('DOMContentLoaded', () => {
  const session = requireRole('inspector');
  if (!session) return;

  initSidebar('inspector', session, 'new-inspection');
  initProfile(session);

  // Set today's date as default
  const today = new Date().toISOString().split('T')[0];
  document.getElementById('inspection_date').value = today;

  // Photo upload
  initUploadZone();

  // Form submission
  document.getElementById('inspection-form').addEventListener('submit', handleSubmit);

  // Reset after submission
  document.getElementById('new-inspection-btn').addEventListener('click', () => {
    document.getElementById('verify-view').classList.add('hidden');
    document.getElementById('form-view').classList.remove('hidden');
    document.getElementById('inspection-form').reset();
    document.getElementById('upload-previews').innerHTML = '';
    document.getElementById('inspection_date').value = today;
  });

  async function handleSubmit(e) {
    e.preventDefault();
    clearError();
    setLoading(true);

    const form = e.target;
    const formData = new FormData(form);

    // Validate required fields
    const reg = formData.get('registrationNumber')?.trim();
    const make = formData.get('make')?.trim();
    const model = formData.get('model')?.trim();
    const date = formData.get('inspectionDate');

    if (!reg || !make || !model || !date) {
      showError('Please fill in all required fields: Registration, Make, Model and Inspection Date.');
      setLoading(false);
      return;
    }

    try {
      const res = await fetch(`${API_BASE}/inspector/inspections`, {
        method: 'POST',
        headers: {
          ...(session.token ? { Authorization: `Bearer ${session.token}` } : {}),
        },
        body: formData,
      });

      let data;
      try { data = await res.json(); } catch { data = {}; }

      if (!res.ok) {
        showError(data.message || data.error || 'Submission failed. Please try again.');
        setLoading(false);
        return;
      }

      // Show verification status
      showVerificationStatus(data);

    } catch (err) {
      showError('Could not reach the server. Check your connection and try again.');
      setLoading(false);
    }
  }

  function showVerificationStatus(data) {
    document.getElementById('form-view').classList.add('hidden');
    document.getElementById('verify-view').classList.remove('hidden');

    const idEl = document.getElementById('submitted-id');
    idEl.textContent = data.inspection_id || data.id || '';

    const hashEl = document.getElementById('step-hash-val');
    if (data.hash) {
      hashEl.textContent = data.hash;
      hashEl.className = 'verify-step-sub hash-display';
    } else {
      hashEl.textContent = 'Hash will be generated by the server';
    }
  }
  const chainEl = document.getElementById('step-chain-val');
  const txHash = data.data?.verification?.transactionHash;
  if (txHash) {
    chainEl.textContent = `Confirmed on-chain — tx ${txHash.slice(0, 10)}...`;
    chainEl.className = 'verify-step-sub hash-display';
  } else {
    chainEl.textContent = 'Anchoring failed or still processing.';
  }

  function setLoading(state) {
    const btn = document.getElementById('submit-btn');
    btn.disabled = state;
    btn.querySelector('.btn-label').classList.toggle('hidden', state);
    btn.querySelector('.btn-spinner').classList.toggle('hidden', !state);
  }

  function showError(msg) {
    const el = document.getElementById('form-error');
    el.textContent = msg;
    el.classList.remove('hidden');
  }

  function clearError() {
    const el = document.getElementById('form-error');
    el.classList.add('hidden');
    el.textContent = '';
  }
});

function initUploadZone() {
  const zone = document.getElementById('upload-zone');
  const input = document.getElementById('photo-input');
  const previews = document.getElementById('upload-previews');

  zone.addEventListener('click', () => input.click());

  zone.addEventListener('dragover', (e) => {
    e.preventDefault();
    zone.classList.add('dragging');
  });

  zone.addEventListener('dragleave', () => zone.classList.remove('dragging'));

  zone.addEventListener('drop', (e) => {
    e.preventDefault();
    zone.classList.remove('dragging');
    renderPreviews(e.dataTransfer.files);
  });

  input.addEventListener('change', () => renderPreviews(input.files));

  function renderPreviews(files) {
    previews.innerHTML = '';
    Array.from(files).forEach(file => {
      if (!file.type.startsWith('image/')) return;
      const reader = new FileReader();
      reader.onload = (e) => {
        const img = document.createElement('img');
        img.src = e.target.result;
        img.className = 'upload-thumb';
        img.alt = file.name;
        previews.appendChild(img);
      };
      reader.readAsDataURL(file);
    });
  }
}
